image: Visual Studio 2022

services:
  - mongodb

shallow_clone: true

cache:
  - packages -> **\packages.config
  - '%LocalAppData%\NuGet\Cache'

before_build:
  - appveyor-retry dotnet restore -v Minimal

build_script:
  - dotnet build Mongrow -c Release --no-restore

test_script:
  - dotnet test Mongrow.Tests -c Release --no-restore